"""empty message

Revision ID: 10aff20ea44a
Revises: 458cc50109c7
Create Date: 2023-11-14 16:43:15.157705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10aff20ea44a'
down_revision = '458cc50109c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showtime', sa.String(length=120), nullable=False),
    sa.Column('movie_name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['movie_name'], ['movie.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showtime')
    # ### end Alembic commands ###
