"""empty message

Revision ID: 20fceacd7528
Revises: 962294b6ada9
Create Date: 2023-10-31 03:28:25.053970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20fceacd7528'
down_revision = '962294b6ada9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_constraint('movies_name_key', type_='unique')
        batch_op.drop_constraint('movies_overview_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_unique_constraint('movies_overview_key', ['overview'])
        batch_op.create_unique_constraint('movies_name_key', ['name'])

    # ### end Alembic commands ###
