"""empty message

Revision ID: 262df014dee6
Revises: 10aff20ea44a
Create Date: 2023-11-14 18:07:59.794397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262df014dee6'
down_revision = '10aff20ea44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showtime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showtime', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
