"""empty message

Revision ID: 458cc50109c7
Revises: d4b17d3115f0
Create Date: 2023-11-14 16:26:07.213763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458cc50109c7'
down_revision = 'd4b17d3115f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('release_date', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.String(length=80), nullable=False),
    sa.Column('overview', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('movies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('release_date', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('rating', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('overview', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='movies_pkey')
    )
    op.drop_table('movie')
    # ### end Alembic commands ###
