"""empty message

Revision ID: 4a3a359f0857
Revises: 262df014dee6
Create Date: 2023-11-16 05:57:45.792980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3a359f0857'
down_revision = '262df014dee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multiplex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadena', sa.String(length=50), nullable=False),
    sa.Column('cinema', sa.String(length=50), nullable=False),
    sa.Column('ciudad', sa.String(length=50), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cinema')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multiplex')
    # ### end Alembic commands ###
