"""empty message

Revision ID: 4c15893ef94e
Revises: fac461bf6813
Create Date: 2023-11-13 04:02:53.340912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c15893ef94e'
down_revision = 'fac461bf6813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('release_date', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.String(length=80), nullable=False),
    sa.Column('overview', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
