"""empty message

Revision ID: 5314361a2088
Revises: 4a3a359f0857
Create Date: 2023-11-17 20:51:02.112336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5314361a2088'
down_revision = '4a3a359f0857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showtime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multiplex_cinema', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'multiplex', ['multiplex_cinema'], ['cinema'])
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showtime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('multiplex_cinema')

    # ### end Alembic commands ###
