"""empty message

Revision ID: 5c7859406dde
Revises: 259518f6f02d
Create Date: 2023-11-02 01:01:11.003130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7859406dde'
down_revision = '259518f6f02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciudades', sa.String(length=80), nullable=False),
    sa.Column('imagen', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ciudades')
    # ### end Alembic commands ###
