"""empty message

Revision ID: 6416c1719df7
Revises: 5314361a2088
Create Date: 2023-11-21 15:33:58.463397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6416c1719df7'
down_revision = '5314361a2088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showtime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('multiplex_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('showtime_movie_name_fkey', type_='foreignkey')
        batch_op.drop_constraint('showtime_multiplex_cinema_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'movie', ['movie_id'], ['id'])
        batch_op.create_foreign_key(None, 'multiplex', ['multiplex_id'], ['id'])
        batch_op.drop_column('multiplex_cinema')
        batch_op.drop_column('movie_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showtime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('multiplex_cinema', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('showtime_multiplex_cinema_fkey', 'multiplex', ['multiplex_cinema'], ['cinema'])
        batch_op.create_foreign_key('showtime_movie_name_fkey', 'movie', ['movie_name'], ['name'])
        batch_op.drop_column('multiplex_id')
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###
