"""empty message

Revision ID: 6def5de72587
Revises: 5c7859406dde
Create Date: 2023-11-02 02:51:43.836483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6def5de72587'
down_revision = '5c7859406dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ciudades')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ciudades', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('imagen', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ciudades_pkey')
    )
    op.drop_table('city')
    # ### end Alembic commands ###
