"""empty message

Revision ID: 82eb5f22a4a5
Revises: 4c15893ef94e
Create Date: 2023-11-13 04:17:52.361820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82eb5f22a4a5'
down_revision = '4c15893ef94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('release_date', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('rating', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('overview', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='movies_pkey')
    )
    # ### end Alembic commands ###
