"""empty message

Revision ID: 93e28d1746b4
Revises: 
Create Date: 2023-11-21 03:11:41.427950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e28d1746b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('release_date', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.String(length=80), nullable=False),
    sa.Column('overview', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movie2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('posterPath', sa.String(), nullable=False),
    sa.Column('overview', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multiplex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadena', sa.String(length=50), nullable=False),
    sa.Column('cinema', sa.String(length=50), nullable=False),
    sa.Column('ciudad', sa.String(length=50), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cinema')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('showtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_name', sa.String(length=120), nullable=True),
    sa.Column('multiplex_cinema', sa.String(length=50), nullable=True),
    sa.Column('showtime', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['movie_name'], ['movie.name'], ),
    sa.ForeignKeyConstraint(['multiplex_cinema'], ['multiplex.cinema'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showtime')
    op.drop_table('user')
    op.drop_table('multiplex')
    op.drop_table('movie2')
    op.drop_table('movie')
    op.drop_table('city')
    # ### end Alembic commands ###
