"""empty message

Revision ID: 962294b6ada9
Revises: 16df604f508a
Create Date: 2023-10-31 01:40:08.567026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962294b6ada9'
down_revision = '16df604f508a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('release_date', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.String(length=80), nullable=False),
    sa.Column('overview', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('overview')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
