"""empty message

Revision ID: f9ad0abe6d30
Revises: 519be40fa192
Create Date: 2023-11-02 01:01:11.702188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ad0abe6d30'
down_revision = '519be40fa192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multiplex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadena', sa.String(length=50), nullable=False),
    sa.Column('cinema', sa.String(length=50), nullable=False),
    sa.Column('ciudad', sa.String(length=50), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cinema')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multiplex')
    # ### end Alembic commands ###
