"""empty message

Revision ID: fac461bf6813
Revises: d4b17d3115f0
Create Date: 2023-11-13 03:57:20.691056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac461bf6813'
down_revision = 'd4b17d3115f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multiplex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadena', sa.String(length=50), nullable=False),
    sa.Column('cinema', sa.String(length=50), nullable=False),
    sa.Column('ciudad', sa.String(length=50), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cinema')
    )
    op.drop_table('movies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('release_date', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('rating', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('overview', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='movies_pkey')
    )
    op.drop_table('multiplex')
    # ### end Alembic commands ###
